language: go

arch:
  - amd64
  - arm64

go:
  - 1.9
  - "1.10"
  - 1.11
  - 1.12
  - 1.13
  - tip

install:
  - go get github.com/stretchr/testify
  - go get -v ./...

matrix:
  allow_failures:
    - go: tip
